### ISSUE TITLE
Add promise support

### ISSUE THREAD

**Issue by balupton** [bevry/ambi#2]
Would be great if this supported returned promise instances. Not sure if this is a task for this, or for taskgroup's task.

@crito as the promise expert, any ideas?

**Comment by christav** [comment]
Been a long time since this was posted, do you still want promise support in this thing? If so, it's be pretty trivial.

Assuming there's a global Promise object that corresponds to Promises/A+ spec, a function that returns a promise would look like a sync function (since it returns a value synchronously). Once you have that value, do something like:
```javascript
    Promise.resolve()
      .then(() => value)
      .then(function onSuccess(v) { callback(null, v); },
        function onError(err) { callback(err); })
```

This would transparently handle both actually synchronous values and Promises in the same code path.

**Comment by balupton** [comment]
Fantastic. Let's do it.

**Comment by christav** [comment]
I'll put together a PR, give me a day or two.

**Comment by balupton** [comment]
Ok, let me update it to the latest conventions first.

**Comment by balupton** [comment]
Ok, it's updated to the latest conventions. Would you be interested in converting it and typechecker to typescript? You can use [boundation](https://github.com/bevry/boundation) to configure the project for typescript.

**Comment by christav** [comment]
@balupton PR sent!

**Comment by balupton** [comment]
Released to v4. Also released v5 which returns a promise instead. Thanks so much for your help on this @christav!
